### ISSUE TITLE
Dropdown and datepicker fields

### ISSUE THREAD

**Issue by codyyc** [freakdesign/shopify-custom-fields#12]
Hey,

I was just wondering if you had considered (or if it is even technically possible) to have dropdown fields with pre-defined options or datepicker fields?

**Comment by colinbrogan** [comment]
I'd like to second cody in the usefulness of this feature. I would try to implement these myself, but the js is minified. Jason, would you happen to be able to get me the source js? I could make a branch of this project and try my hand at adding a few features.

**Comment by colinbrogan** [comment]
I'll go ahead and give you my email address, in the event that you want to release your source js in the wild:
colinbrogan@gmail.com

**Comment by codyyc** [comment]
I'd happily help out and contribute too.

Following this format, I'd also add 

[_d?format=DD/MM/YYYY]

Which could just be interpreted by jQuery datepicker.

**Comment by dabernathy89** [comment]
> I would try to implement these myself, but the js is minified. Jason, would you happen to be able to get me the source js?

Seconding this - @freakdesign, any chance that the source JS could be included in the repo to better facilitate community contributions?

**Comment by asyncopation** [comment]
Hi all, just stumbled upon this plugin.  Why was this issue closed?  Fields with predetermined options (dropdown) would be immensely useful.  Thanks.
