### ISSUE TITLE
No custom fields found

### ISSUE THREAD

**Issue by mguikema** [freakdesign/shopify-custom-fields#16]
![shopify-admin-pdp](https://cloud.githubusercontent.com/assets/1019329/7769507/91c462b8-0084-11e5-9b0f-65bcefefaa41.png)
We have been using the plugin for Shopify for a couple of months now with no issues. But last week the metafields are not visible/editable anymore. Could this have to do with the latest Shopify admin interface update?  Could you help us out with the issue?

**Comment by freakdesign** [comment]
Can you confirm that you are using the [latest version](http://freakdesign.com.au/pages/shopify-custom-fields) served from the CDN (and not github)? Are you using the Chrome extension or bookmarklet?

I've tested it here and don't see that issue. If you are 100% sure that you've setup the fields to show on products and no longer see the fields I have to wonder if you are running an old version.

**Comment by mguikema** [comment]
Sorry for the late response.
I'm using the Chrome extension v0.0.4. For Chrome Version 43.0.2357.65 beta (64-bit) on osx 10.9.5.
I'm not getting any errors. Our content editor had the same problem with the extension. And they updated the extension trying to fix the problem, so they must have the same version.

**Comment by freakdesign** [comment]
As far as I can see the extension is working correctly. I've tested on various platforms and stores without issue. Show me a screen capture of how you've set up the initial metafields at store level.

**Comment by mguikema** [comment]
I'm sorry. I made was under the impression that our client was using the shopify-custom-fields extension. But i was wrong, they where using the Shopify FD extension. When i activate this extension, it's working again. I'm very sorry for your time.

**Comment by freakdesign** [comment]
No problem! Glad you figured it out ;)
