### ISSUE TITLE
Add date field support

### ISSUE THREAD

**Issue by freakdesign** [freakdesign/shopify-custom-fields#28]
Nice and simple really. Add in the ability to use a HTML5 date field.

**Comment by freakdesign** [comment]
The new markers added are `[_n]` for a number field and `[_d]` for a date field.

**Comment by tng10** [comment]
Hey @freakdesign,
Do you think is possible to have _datetime_ field as well?
http://w3c.github.io/html-reference/input.datetime-local.html
