### ISSUE TITLE
CF not loading variant meta-fields on products

### ISSUE THREAD

**Issue by softlimit** [freakdesign/shopify-custom-fields#30]
Seems like something has changed in the past couple days as CF is not loading variant meta-fields on products all of the sudden. Any idea if this is a major rollout change that needs to be adjusted for or something else?

And, as always, thanks for making this very major and necessary extension!

**Comment by freakdesign** [comment]
Thanks for the issue report @softlimit - I'll take a look at this now and see what's going on.

**Comment by softlimit** [comment]
@freakdesign Amazing. Thank you!

**Comment by softlimit** [comment]
@freakdesign Seems like this issue may be rearing it's head again? I have a metafield that has been working a-ok since the previous discussion... stopped working within the past few days. Seems fine if I drop down to only using [p], but as soon as [v] is in play, the custom field disappears. Are you seeing the same thing?

**Comment by freakdesign** [comment]
If I setup a metafield with [v] I see this in the admin in Chrome:
![image](https://cloud.githubusercontent.com/assets/1378665/18488142/2e776f54-79c6-11e6-93a8-5c54a5d8de58.png)

That used the setup metafield of `c_f.prepped-earlier` and the value of `[v] Here's a field I made earlier...`.

If you don't see that let's get some info on the setup metafield and browser so I can try and replicate what you see.

**Comment by softlimit** [comment]
@freakdesign You are totally right. Sorry. I had expected to see the Product Custom Field on a product that didn't have any variants and didn't realize that, even sans variant, the product page was loading the CF down at the variant section. My bad. Issue resolved... user error. Thanks for investigating!
