### ISSUE TITLE
Custom Fields installed but not able to add shop level metafield

### ISSUE THREAD

**Issue by julbr** [freakdesign/shopify-custom-fields#31]
I've installed the Chrome extension (also tried the bookmarklet on Safari), and I see the section 'Custom Fields' in the Admin product page `/admin/products/xxx`, which shows "No custom fields found".
When I go to `/admin/settings/general` though, there is not `Custom Fields` section...
So i'm stuck without being able to add shop level metafield.
Any suggestions? Thanks a lot! Your tool looks great, I hope I can use it and eventually donate!

**Comment by freakdesign** [comment]
The Custom Fields tool was originally conceived as a tool that developers might give to their clients. As such, the developer would add the setup metafields **before** handing the project over to the client so the client just had to run to tool and go (and not worry about the setup side).

If you need to add the setup metafields you could use:

- ShopifyFD,
- another metafield editor of your choosing, or 
- the API directly

It is a common request for the setup to be part of the tool directly so version 2 of the tool (in production) will give those controls. 

Not everyone needs to use Custom Fields tool either. For some ShopifyFD is perfect and others might prefer to use the built in metafield editor that's part of the [Shopify bulk editing tool](https://www.shopify.com/partners/blog/53573123-secrets-of-the-shopify-bulk-editor).

**Comment by julbr** [comment]
All is clear now!
