### ISSUE TITLE
Fields editor box not showing in Settings

### ISSUE THREAD

**Issue by lmartins** [freakdesign/shopify-custom-fields#33]
Until recently I could use Chrome's extension to load a settings box in Shopify's preferences that would allow me, among other things, configure the whitelist setting.

Currently I can't make that box appear, no matter what I try. Just me or is this a know issue?

**Comment by freakdesign** [comment]
@lmartins This tool does not load anything on the preferences pages. Although minified, you can see the url filtering near the end of the code. 

To save you hunting through the code, the only pages that the tool runs on are:

- articles
- pages
- products
- customers
- orders
- collections
- smart_collections
- custom_collections

There has been thoughts of adding CF to the preferences page, but it's always been pushed off to ShopifyFD instead.

**Comment by lmartins** [comment]
hi, thanks for your feedback.
I should also apologize as I should have made a better job explaining my steps. I am using both extensions, including FD, but no matter what I can't replicate previous behaviour. Im away from the computer but I'll try tomorrow to spot any errors and see if I can provide more info here.

Thanks again.

**Comment by lmartins** [comment]
@freakdesign you wont believe this but I was banging my head on this for the last 2 days, without any luck. Today, went to try it again and provide more details here and it worked. Go figure...

![screenshot 2016-07-14 19 00 18](https://cloud.githubusercontent.com/assets/151981/16850065/3b0e6bc4-49f5-11e6-9781-adfd1ae73d4a.png)
