### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by dominikwilkowski** [freakdesign/shopify-custom-fields#4]
Hey there,

this is a fantastic idea and a great tool. I would love to help in the development or otherwise but first:

Would you consider adding the source up as a unminified version?

I mean jsbeautifier.org can only take it so far ;)

**Comment by martinheidegger** [comment]
1 year+ ago...

**Comment by freakdesign** [comment]
Yes, this question is over a year old.
:birthday:

Since the age of the question may be of concern to people let's close it. The OS plan exists, but no sense getting peoples hopes up on a date, especially when there's a new version in the works.

**Comment by namwen** [comment]
I'm curious if you have any intention of opening this up again @freakdesign . This app is incredibly useful and I'd love to see it get more love. I'm sure there are others who would be happy to contribute as well.
