### ISSUE TITLE
Shopify Refusing to Load Custom Fields Tool

### ISSUE THREAD

**Issue by Jerad-M** [freakdesign/shopify-custom-fields#40]
Shopify appears to be rejecting the request to the script as unsafe (running from a bookmarklet, not the extension).
![shopify_custom_fields](https://cloud.githubusercontent.com/assets/14872608/22651674/d4d8c82c-ec51-11e6-981b-19f49dbf3b05.png)

**Comment by freakdesign** [comment]
@Jerad-M Amazon S3 is no longer on the whitelisted domain list. Try using the link at the bottom of [this page](https://freakdesign.com.au/pages/shopify-custom-fields) for a version hosted on Shopify.

**Comment by Jerad-M** [comment]
That does the trick, thanks!
