### ISSUE TITLE
Polaris update breaks the Custom Fields extension

### ISSUE THREAD

**Issue by ktaftaf** [freakdesign/shopify-custom-fields#43]
I cant get any fields to show up after the polaris update. Was curious if this was an issue you were aware of, or if I'm the only one having this problem.

**Comment by freakdesign** [comment]
It's a known issue and you won't be the only one experiencing it. Working on ShopifyFD at the moment, but will jump onto Custom Fields soon. 

I appreciate you making the issue regardless. Will be helpful for others to see.

**Comment by freakdesign** [comment]
The Polaris update (https://github.com/freakdesign/shopify-custom-fields/commit/fba000a22cf3c7fe8226c83cb2b743bd656a7a78) should see better results here. Clear the cache and give it a try when ready.
